#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# firstpage:
#   path: /firstpage
#   controller: App\Controller\FirstPageController.php

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\FirstPageController::number